### ISSUE TITLE
I've hundreds of peptides, one protein

### ISSUE THREAD

**Issue by Dmorgen** [martinry/proteasy#1]
Hi, how do I run the code looking for proteases based on peptide sequences, for just one protein? the script wants the peptide and protein vector to have the same lengths...

**Comment by martinry** [comment]
Hi, repeat the protein accession in a vector for as many peptide sequences you have.

```
peptide <- c("FEEVSGNVSPGTR", "FVSETESR", "LLVVYPW", "ITLLSAL")
protein <- rep("P02671", length(peptide))
res <- findProtease(protein = protein, peptide = peptide, organism = "Homo sapiens")
```

**Comment by Dmorgen** [comment]
Thanks! 
another question - iI've couple of dozens of protein uniprot accessions that give an error that they couldn't be mapped. is there a way to add to the "findProtease" command to ignore positions in both vectors that could not be mapped? thanks!

**Comment by martinry** [comment]
The function gives a warning that the accessions can not be mapped. These accessions and corresponding peptide sequences are automatically excluded from the search. So as I understand you, the default behavior is already what you requested.

**Comment by Dmorgen** [comment]
Thanks!
D.
